<?php
return array(

	'root'					=> '/',
	'host'					=> 'http://globiks',
	'upload_root'			=> '/upload/',
	'upload_host'			=> 'http://globiks/upload',
	'cache_root'			=> '/cache/',
	'is_site_on'			=> '1',
	'off_reason'			=> 'Идут технические работы',
	'sitename'				=> 'InstantCMS 2.0',
	'hometitle'				=> 'InstantCMS 2.0',
	'date_format'			=> 'd.m.Y',
	'date_format_js'		=> 'dd.mm.yy',
	'time_zone'				=> 'Europe/Moscow',
	'template'				=> 'globiks',
	'db_host'				=> 'localhost',
	'db_base'				=> 'globiks',
	'db_user'				=> 'root',
	'db_pass'				=> '',
	'db_prefix'				=> 'cms_',
	'db_users_table'		=> 'cms_users',
	'language'				=> 'ru',
	'metakeys'				=> 'ключевые, слова, сайта',
	'metadesc'				=> 'Описание сайта',
	'ct_autoload'			=> 'frontpage',
	'ct_default'			=> 'content',
	'frontpage'				=> 'none',
	'debug'					=> '1',
	'emulate_lag'			=> '',
	'cache_enabled'			=> '',
	'cache_method'			=> 'files',
	'cache_ttl'				=> '300',
	'cache_host'			=> 'localhost',
	'cache_port'			=> '11211',
	'min_html'				=> '',
	'merge_css'				=> '',
	'merge_js'				=> '',
	'mail_transport'		=> 'mail',
	'mail_from'				=> 'noreply@example.com',
	'mail_smtp_server'		=> 'smtp.example.com',
	'mail_smtp_port'		=> '25',
	'mail_smtp_auth'		=> '1',
	'mail_smtp_user'		=> 'user@example.com',
	'mail_smtp_pass'		=> '',
	'is_check_updates'		=> '1',
	'ctype_default'			=> '',
	'is_no_meta'			=> '',
	'mail_smtp_enc'			=> '0',

);
